name: Pull Request

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - 'docs/**'

jobs:
  CI:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run the linter, formatter, and TypeScript compiler
        run: npm run lint && npm run build

      - name: Publish
        run: npx vsce publish --no-update-package-json --no-git-tag-version -p ${{ secrets.AZURE_TOKEN }} ${{ github.ref_name }}
