name: Pull Request

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - 'docs/**'

jobs:
  CI:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run the pretest suite
        run: npm run test
