name: Pull Request

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - 'docs/**'

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run the linter, formatter, and TypeScript compiler
        run: npm run lint && npm run build
