name: Tag

on:
  push:
    tags:
      - '*.*.*'

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install -g pnpm; pnpm install

      - name: Install dependencies
        run: pnpm install

      - name: Publish
        run: npx vsce publish --no-update-package-json --no-git-tag-version -p ${{ secrets.AZURE_TOKEN }} ${{ github.ref_name }}
